### ISSUE TITLE
How do you identify global trends?

### ISSUE THREAD

**Issue by jamiecropley** [radhikasethi2011/awesome-business-ideas#1]
How do you identify global trends?

**Comment by radhikasethi2011** [comment]
Hi! Global trends are something that is trending right now, on a global scale. For example, the need to use online video call apps like Zoom and Google Meet. 
Another global trend at the moment is the digitalization of college exams, college education. 
It's basically something that is being hyped up about currently and is something that we as a community should work on, to make it better and more accessible to others. 
Makes sense?

**Comment by jamiecropley** [comment]
Yes, but how do you 100% determine that? Because that would be heavily open to bias if you are just using such a generic approach? I mean google trends is a good starting point, but I think from the video this was based on it talked more about like business trends and such. I mean there has to be a data resource out there somewhere? The thing is the more factual data you have backing your new business idea I think the more attraction it would have to potential investors. Example, you seek investment in your app idea, the investor tells you this is not a trend based on there factual and data research etc... and such. I mean I am not criticising here, just trying to understand more than anything.

**Comment by radhikasethi2011** [comment]
You're right. Maybe there is a factual data resource. I will look into it. But from Allie's point of view, I think it was about the current global trends - something that you read in the news/internet. 
But good of you to bring it up, I'll look into this.

**Comment by jamiecropley** [comment]
Yeah I just mean there is no harm trying ideas from the news in that respect in my opinion if they are low risk. But higher risk ideas when you seek a lot of investment I think having such a creative approach could possibly be harmful, not sure on that even though. I will look into it as well, I tried to message Allie for more context but she did not answer the question. I will update here if I find out anything that can provide some good context. I think google trends is good in this respect but again it can be a bit vague perhaps?

**Comment by radhikasethi2011** [comment]
That's true. I will look into the same. Closing this issue for now!
